//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 10:37:33 AM EET 
//

package com.xylugah.mnsgmk.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for descriptionType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="descriptionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DEDUCTION_IN_FULL"/>
 *     &lt;enumeration value="VAT_EXEMPTION"/>
 *     &lt;enumeration value="OUTSIDE_RB"/>
 *     &lt;enumeration value="IMPORT_VAT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "descriptionType")
@XmlEnum
public enum DescriptionType {

	DEDUCTION_IN_FULL, VAT_EXEMPTION, OUTSIDE_RB, IMPORT_VAT;

	public String value() {
		return name();
	}

	public static DescriptionType fromValue(String v) {
		return valueOf(v);
	}

}
