//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 10:37:33 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3schools.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.xylugah.mnsgmk.entity;
