//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 10:37:33 AM EET 
//


package com.xylugah.mnsgmk.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ �� ������� (�������, �������), ������������� ������
 * 
 * <p>Java class for rosterList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rosterList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rosterItem" type="{http://www.w3schools.com}rosterItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="totalCostVat" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="totalExcise" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="totalVat" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="totalCost" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rosterList", propOrder = {
    "rosterItem"
})
public class RosterList {

    @XmlElement(required = true)
    protected List<RosterItem> rosterItem;
    @XmlAttribute(name = "totalCostVat", required = true)
    protected BigDecimal totalCostVat;
    @XmlAttribute(name = "totalExcise", required = true)
    protected BigDecimal totalExcise;
    @XmlAttribute(name = "totalVat", required = true)
    protected BigDecimal totalVat;
    @XmlAttribute(name = "totalCost", required = true)
    protected BigDecimal totalCost;

    /**
     * Gets the value of the rosterItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rosterItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRosterItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RosterItem }
     * 
     * 
     */
    public List<RosterItem> getRosterItem() {
        if (rosterItem == null) {
            rosterItem = new ArrayList<RosterItem>();
        }
        return this.rosterItem;
    }

    /**
     * Gets the value of the totalCostVat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalCostVat() {
        return totalCostVat;
    }

    /**
     * Sets the value of the totalCostVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalCostVat(BigDecimal value) {
        this.totalCostVat = value;
    }

    /**
     * Gets the value of the totalExcise property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalExcise() {
        return totalExcise;
    }

    /**
     * Sets the value of the totalExcise property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalExcise(BigDecimal value) {
        this.totalExcise = value;
    }

    /**
     * Gets the value of the totalVat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalVat() {
        return totalVat;
    }

    /**
     * Sets the value of the totalVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalVat(BigDecimal value) {
        this.totalVat = value;
    }

    /**
     * Gets the value of the totalCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalCost() {
        return totalCost;
    }

    /**
     * Sets the value of the totalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalCost(BigDecimal value) {
        this.totalCost = value;
    }

}
