//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 10:37:33 AM EET 
//


package com.xylugah.mnsgmk.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ��������� ������������������ � ���������������
 * 
 * <p>Java class for senderReceiver complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="senderReceiver">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="consignors" type="{http://www.w3schools.com}consignorList" minOccurs="0"/>
 *         &lt;element name="consignees" type="{http://www.w3schools.com}consigneeList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "senderReceiver", propOrder = {
    "consignors",
    "consignees"
})
public class SenderReceiver {

    protected ConsignorList consignors;
    protected ConsigneeList consignees;

    /**
     * Gets the value of the consignors property.
     * 
     * @return
     *     possible object is
     *     {@link ConsignorList }
     *     
     */
    public ConsignorList getConsignors() {
        return consignors;
    }

    /**
     * Sets the value of the consignors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsignorList }
     *     
     */
    public void setConsignors(ConsignorList value) {
        this.consignors = value;
    }

    /**
     * Gets the value of the consignees property.
     * 
     * @return
     *     possible object is
     *     {@link ConsigneeList }
     *     
     */
    public ConsigneeList getConsignees() {
        return consignees;
    }

    /**
     * Sets the value of the consignees property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsigneeList }
     *     
     */
    public void setConsignees(ConsigneeList value) {
        this.consignees = value;
    }

}
